version: "3.7"
services:
  # PostgreSQL for Airflow
  airflow-postgres:
    image: postgres:13
    container_name: airflow-postgres
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    ports:
      - "5432:5432"
    volumes:
      - airflow-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 10s
      retries: 5

  # Redis for Airflow
  redis:
    image: redis:7.2-bookworm
    container_name: redis
    expose:
      - "6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 30s
      retries: 50

  # Airflow Webserver
  airflow-webserver:
    image: apache/airflow:2.10.5
    container_name: airflow-webserver
    environment:
      AIRFLOW__CORE__EXECUTOR: CeleryExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CELERY__RESULT_BACKEND: db+postgresql://airflow:airflow@airflow-postgres/airflow
      AIRFLOW__CELERY__BROKER_URL: redis://:@redis:6379/0
    ports:
      - "8090:8080"
    depends_on:
      redis:
        condition: service_healthy
      airflow-postgres:
        condition: service_healthy

  # PostgreSQL for DataHub
  datahub-postgres:
    image: postgres:13
    container_name: datahub-postgres
    environment:
      POSTGRES_USER: datahub
      POSTGRES_PASSWORD: datahub
      POSTGRES_DB: datahub-pg
    ports:
      - "5433:5432"
    volumes:
      - datahub-postgres-data:/var/lib/postgresql/data

  # Kafka for DataHub
  broker:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka-broker
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:${DATAHUB_MAPPED_KAFKA_BROKER_PORT:-9092}
    ports:
      - "9092:${DATAHUB_MAPPED_KAFKA_BROKER_PORT:-9092}"
    depends_on:
      zookeeper:
        condition: service_healthy

  # Zookeeper for Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:${DATAHUB_CONFLUENT_VERSION:-7.4.0}
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      interval: 10s
      retries: 3
      start_period: 20s
      test: ["CMD", "nc", "-z", "localhost", "2181"]
      timeout: 5s

  # Elasticsearch for DataHub Search Indexing
  elasticsearch:
    image: elasticsearch:${DATAHUB_SEARCH_TAG:-7.10.1}
    container_name: elasticsearch
    environment:
    - discovery.type=single-node

  # DataHub GMS (Global Metadata Service)
  datahub-gms:
    image: acryldata/datahub-gms:${DATAHUB_VERSION:-head}
    container_name: datahub-gms
    environment:
      EBEAN_DATASOURCE_DRIVER: org.postgresql.Driver
      EBEAN_DATASOURCE_HOST: datahub-pg:5432
      EBEAN_DATASOURCE_URL: jdbc:postgresql://datahub-postgres:5432/datahub-pg

volumes:
  airflow-postgres-data:
  datahub-postgres-data: